//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankOfFiji_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BankAccount()
        {
            this.AutoPayments = new HashSet<AutoPayments>();
            this.AutoPayments1 = new HashSet<AutoPayments>();
            this.LoanApplications = new HashSet<LoanApplications>();
            this.Transactions = new HashSet<Transactions>();
            this.Transactions1 = new HashSet<Transactions>();
        }
    
        public int accountNo { get; set; }
        public int userId { get; set; }
        public int accountTypeId { get; set; }
        public System.DateTime startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public decimal debitBal { get; set; }
        public decimal creditBal { get; set; }
        public decimal totalInterest { get; set; }
        public int taxId { get; set; }
        public int accountStatusId { get; set; }
        public Nullable<System.DateTime> interestdate { get; set; }
        public Nullable<decimal> nonresident_tax { get; set; }
        public Nullable<decimal> withdrawal_tax { get; set; }
        public Nullable<int> withdrawal_monthly_counter { get; set; }
        public Nullable<decimal> business_tax { get; set; }
    
        public virtual AccountStatus AccountStatus { get; set; }
        public virtual AccountType AccountType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutoPayments> AutoPayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutoPayments> AutoPayments1 { get; set; }
        public virtual TaxRates TaxRates { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanApplications> LoanApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transactions> Transactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transactions> Transactions1 { get; set; }
    }
}
