//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankOfFiji_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerProfile
    {
        public System.Guid rowId { get; set; }
        public int customerId { get; set; }
        public int customerTypeId { get; set; }
        public Nullable<System.DateTime> dateOfBirth { get; set; }
        public string postal { get; set; }
        public string gender { get; set; }
        public string address { get; set; }
        public string FNPFNumber { get; set; }
        public string martialStatus { get; set; }
        public string occupation { get; set; }
        public string TIN { get; set; }
        public string passportNumber { get; set; }
        public string residentialType { get; set; }
        public string businessName { get; set; }
        public string sourceOfFunds { get; set; }
        public string employerName { get; set; }
        public Nullable<decimal> salaryPerAnnum { get; set; }
        public byte[] DOBCertificate { get; set; }
        public byte[] FNPFCertificate { get; set; }
        public byte[] TINLetter { get; set; }
        public byte[] businessLicense { get; set; }
        public byte[] passportCpy { get; set; }
        public byte[] photoID { get; set; }
    
        public virtual CustomerType CustomerType { get; set; }
        public virtual Users Users { get; set; }
    }
}
