//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankOfFiji_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternationalTransfer
    {
        public string ITransfer_ID { get; set; }
        public string ITState_ID { get; set; }
        public int sourceAccount { get; set; }
        public int destinationAccount { get; set; }
        public decimal amount { get; set; }
    
        public virtual BankAccount BankAccount { get; set; }
        public virtual Transfer_State Transfer_State { get; set; }
    }
}
