//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankOfFiji_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanRecords
    {
        public int loanApplicationNo { get; set; }
        public System.DateTime repaymtStartDate { get; set; }
        public System.DateTime repaymtEndDate { get; set; }
        public int LoanStatusId { get; set; }
    
        public virtual LoanApplications LoanApplications { get; set; }
        public virtual LoanStatus LoanStatus { get; set; }
    }
}
