//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankOfFiji_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class Notification
    {
        public int NotificationID { get; set; }
        public string NotificationType { get; set; }
        public string NotificationStatus { get; set; }
    }
}
